from typing import Any

class Model:
    def __init__(
        self, id: int, name: str, fields: list[str], templates: list[Any], css: str = ""
    ) -> None: ...

class Note:
    def __init__(self, model: Model, fields: list[str]) -> None: ...

class Deck:
    def __init__(self, id: int, name: str, description: str = "") -> None: ...
    def add_note(self, note: Note) -> None: ...

class Package:
    def __init__(self, deck: Deck) -> None: ...
    def write_to_file(self, file: str, timestamp: float | None = None) -> None: ...
